version: "3"
services:
    strapi:
        container_name: strapi
        build:
            context: ../backend
            dockerfile: Dockerfile
        image: strapi:latest
        restart: unless-stopped
        env_file: .env
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_HOST: strapiDB
            DATABASE_PORT: 3306
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
            APP_KEYS: ${APP_KEYS}
            NODE_ENV: ${NODE_ENV}
        volumes:
            - ../backend/config:/opt/app/config
            - ../backend/src:/opt/app/src
            - ../backend/package.json:/opt/package.json
            - ../backend/package-lock.json:/opt/package-lock.json
            - /opt/app/public:/opt/app/public
        ports:
            - "127.0.0.1:1337:1337"
        networks:
            - strapi
        depends_on:
            - strapiDB

    strapiDB:
        container_name: strapiDB
        platform: linux/amd64
        restart: unless-stopped
        env_file: .env
        image: mysql:8
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        volumes:
            - strapi-data:/var/lib/mysql
        ports:
            - "127.0.0.1:3306:3306"
        networks:
            - strapi

volumes:
    strapi-data:

networks:
    strapi:
